/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bcc91617-794e-49af-aaeb-66b5a61fe2eb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_ExYxWtoTV",
    "aws_user_pools_web_client_id": "3v51ucoukstcuugmon0sgfcu35",
    "oauth": {}
};


export default awsmobile;
